apps/api/urls.py
from django.urls import path

from .views import home, ranking_sellers, ranking_publishings, get_category

urlpatterns = [
    path('', home, name='home'),
    path('ranking_sellers/', ranking_sellers, name='ranking_sellers'),
    path('ranking_publishings/', ranking_publishings, name='ranking_publishings'),
    path('connect_ml/', get_category, name='connect_ml'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.api.urls', 'apiv1'), namespace='apiv1'),),
    #path('apiv1/', include(('apps.api.urls', 'apiv1'), namespace='apiv1'),),
]

apps/api/models.py
from django.db import models

# Create your models here.

apps/api/views.py
from __future__ import print_function
import time
import meli
from meli.rest import ApiException
from pprint import pprint

from django.shortcuts import render

from .services import get_sellers_by_category, get_publishings_more_expensive, get_info_seller, get_token

# Defining the host is optional and defaults to https://api.mercadolibre.com
# See configuration.py for a list of all supported configuration parameters.
configuration = meli.Configuration(
    host="https://api.mercadolibre.com"
)


def home(request):
    """
    Muestra ver la pantalla de inicio con el menú principal.
    """

    tenmplate_name = "home.html"

    return render(request, tenmplate_name, {})


def ranking_publishings(request):
    """
    Muestra el listado de la 20 publicaciones más caras en la categoría MLA352679
    """

    template_name = "publishings_list.html"

    data = []  # Guardo las publicaciones en una lista que sera pasada al template
    row = {}  # Guardo el contentido de cada publicación en un diccionario con una estructura que solo contiene los
    # datos soliccitados y que formará parte de la lista de resultados

    publishings = get_publishings_more_expensive()  # Traigo info de la categoría y sus publicaciones ordenadas por
    # precio mas caro
    data_results = publishings.get('results')  # Obtengo solo los datos de las publicaciones.

    # Recorro cada publicación y cargo solo los datos en la lista que será utilizada en el template
    for result in data_results:
        row['titulo'] = result.get('title')
        row['precio'] = result.get('price')
        row['enlace'] = result.get('permalink')
        data.append(row.copy())

    context = {
        'res': data[:20]
    }

    return render(request, template_name, context)


def ranking_sellers(request):
    """
    Muestra el listado de los 5 vendedores que más vendieron en la categoría MLA352679
    """

    template_name = "sellers_list.html"

    data_results = []  # Guarda todas las publicaciones de la categoría MLA352679

    # Este for me permite ir iterando en las publicaciones de la categoría para solo guardar en la lista los ids únicos
    # de cada vendor
    for i in range(0, 1000, 50):  # Hago for para ir pasando de pagina de a 50

        publishings = get_sellers_by_category(i)  # Traigo info de la categoría pasando un nuevo valor de offset en
        # cada iteración, es decir voy saltando de a 50 registros

        data_results.extend(publishings.get('results'))  # Guardo solo el conjunto de publicaciones obtenidas

    seller_ids = []  # Guardo los id no repetidos(únicos) de los vendedores de la categoría.

    # Este for me permite ir almacenando los id de los vendedores pero dichos id no deben estar repetidos
    for result in data_results:  # Itero en cada publicación

        seller_id = result.get('seller').get('id')  # Obtengo el id del vendedor de la publicación

        if seller_id not in seller_ids:  # Verifico si id esta en la lista, sino no esta agrego el id
            seller_ids.append(seller_id)

    seller = {}  # Almaceno los datos de un vendedor
    ranking_sellers = []  # Almaceno los datos de los vendedores que se van a mostar en el template

    # Con este for traigo toda la info del vendedor
    for seller_id in seller_ids:

        info_seller = get_info_seller(seller_id)  # Obtengo los datos (en ellos las publicaciones) de un vendedor en la
        # categoría MLA352679

        seller['nickname'] = info_seller.get('seller').get('nickname')

        pubs = info_seller.get('results')  # Obtengo las publicaciones del vendedor en la categoría MLA352679

        # sold_total = 0
        # for pub in pubs:
        #     sold_total = sold_total + pub.get('sold_quantity')
        # seller['sold_total'] = sold_total

        seller['sold_total'] = sum(item["sold_quantity"] for item in pubs)  # Sumo el total de lo vendido en cada
        # publacición y lo almaceno como total del vendedor en la categoría MLA352679
        ranking_sellers.append(seller.copy())

    sorted_ranking = sorted(ranking_sellers, key=lambda x: x['sold_total'], reverse=True)  # Con los totales de los
    # vendedores en la categoría, procedo a ordenar de mayor cantidad vendida a mennor

    context = {
        'res': sorted_ranking[:5],
    }

    return render(request, template_name, context)


def get_category(request):

    template_name = "connect_meli.html"

    # Enter a context with an instance of the API client
    with meli.ApiClient() as api_client:
        # Create an instance of the API class
        api_instance = meli.RestClientApi(api_client)
        # https://api.mercadolibre.com/categories/MLA352679
        resource = 'sites/MLA/categories'  # A resource example like items, search, category, etc.
        token = get_token()
        access_token = token['access_token']
    try:
        # Resource path GET
        api_response = api_instance.resource_get(resource, access_token)
        # pprint("View" + api_response)

    except ApiException as e:
        print("Exception when calling RestClientApi->resource_get: %s\n" % e)

    context = {
        'res': api_response,
    }
    return render(request, template_name, context)

apps/api/templates/connect_meli.html
{% extends "base.html" %}

{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3>Listado de Categorías en Mercado Libre - Con Usuario Autenticado</h3>
    </div>

    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="tabla">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                </tr>
            </thead>
            <tbody>
                {% for item in res %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock contenido %}

apps/api/templates/home.html
{% extends "base.html" %}

{% block contenido %}
<div class="row"></div>
    <h1>Bienvenido</h1>
</div>
{% endblock contenido %}

apps/api/templates/publishings_list.html
{% extends "base.html" %}

{% block contenido %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3>Listado de publicaciones mas caras</h3>
    </div>

    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="tabla">
            <thead>
                <tr>
                    <th colspan="2">
                        Listado de Publicaciones de la categoria MLA352679 (SmartWatch) ordenadas descendentemente con respecto al precio
                        <a href="javascript:location.reload()" class="btn btn-outline btn-success  dim"><i class="fa fa-refresh"></i> Actualizar página</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for data in res %}
                    {% for key, value in data.items %}
                        <tr>
                            <td>{{ key|upper }}</td>

                            {% if key == 'enlace' %}
                                <td><a href="{{ value }}" target="_blank">Ver Producto</a></td>
                            {% else %}
                                {% if key == 'precio' %}
                                    <td>$ {{ value }}</td>
                                {% else %}
                                    <td>{{ value }}</td>
                                {% endif %}
                            {% endif %}
                        </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock contenido %}

apps/api/templates/sellers_list.html
{% extends "base.html" %}

{% block contenido %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3>Listado de los 5 vendedores que mas venden</h3>
    </div>
    <br>
    <div class="text-center">
        <a href="javascript:location.reload()" class="btn btn-outline btn-success  dim"><i class="fa fa-refresh"></i> Actualizar página</a>
    </div>
    <div class="panel-body">

        <table width="100%" class="table table-striped table-bordered table-hover" id="tabla">
            <thead>
                <tr>
                    <th>Apodo</th>
                    <th>Total Vendido</th>
                </tr>
            </thead>
            <tbody>
                {% for item in res|dictsort:"sold_total" %}
                <tr>
                    <td>{{ item.nickname }}</td>
                    <td>{{ item.sold_total }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock contenido %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Panel de Control</title>

    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/font-awesome.css' %}" rel="stylesheet">

    <!-- Toastr style -->
    <link href="{% static 'base/css/toastr.min.css' %}" rel="stylesheet">

    <!-- Gritter -->
    <link href="{% static 'base/css/jquery.gritter.css' %}" rel="stylesheet">

    <link href="{% static 'base/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/style.css' %}" rel="stylesheet">

    <!--datatable-->
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

    <!-- JQuery confirm -->
    <link href="{% static 'base/jquery_confirm/jquery-confirm.min.css' %}" rel="stylesheet">

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />

    <!-- Bootstrap Table -->
    <!--<link href="{% static 'base/bootstraptable/dist/bootstrap-table.min.css' %}" rel="stylesheet">-->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
    <!-- Select2 -->
    <link href="{% static 'base/css/select2.min.css' %}" rel="stylesheet">
    <style>
        canvas {
        height : 500px;
        width : 500px;
        border : 2px black solid;
        }
    </style>
</head>

<body>
    <div id="wrapper">
        {% include 'side_bar.html' %}

        <div id="page-wrapper" class="gray-bg dashbard-1">
            {% include 'top_bar.html' %}

            {% block contenido %}

            {% endblock contenido %}

        </div>
        <div class="modal fade" id="popup"></div>

        <script src="{% static 'base/js/efect.js' %}"></script>
        <!--<script src="{% static 'base/js/jquery.min.js' %}"></script>-->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

        <!-- Mainly scripts -->
        <script src="{% static 'base/js/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'base/js/popper.min.js' %}"></script>
        <script src="{% static 'base/js/bootstrap.js' %}"></script>
        <script src="{% static 'base/js/jquery.metisMenu.js' %}"></script>
        <script src="{% static 'base/js/jquery.slimscroll.min.js' %}"></script>
        <!-- Flot -->
        <script src="{% static 'base/js/jquery.flot.js' %}"></script>
        <script src="{% static 'base/js/jquery.flot.tooltip.min.js' %}"></script>
        <script src="{% static 'base/js/jquery.flot.spline.js' %}"></script>
        <script src="{% static 'base/js/jquery.flot.resize.js' %}"></script>
        <script src="{% static 'base/js/jquery.flot.pie.js' %}"></script>

        <!-- Peity -->
        <script src="{% static 'base/js/jquery.peity.min.js' %}"></script>
        <script src="{% static 'base/js/peity-demo.js' %}"></script>

        <!-- Custom and plugin javascript -->
        <script src="{% static 'base/js/inspinia.js' %}"></script>
        <script src="{% static 'base/js/pace.min.js' %}"></script>

        <!-- jQuery UI -->
        <script src="{% static 'base/js/jquery-ui.min.js' %}"></script>

        <!-- GITTER -->
        <script src="{% static 'base/js/jquery.gritter.min.js' %}"></script>

        <!-- Sparkline -->
        <script src="{% static 'base/js/jquery.sparkline.min.js' %}"></script>

        <!-- Sparkline demo data  -->
        <script src="{% static 'base/js/sparkline-demo.js' %}"></script>

        <!-- ChartJS-->
        <script src="{% static 'base/js/Chart.min.js' %}"></script>

        <!--datatable-->
        <script src="{% static 'base/datatables/datatables.min.js' %}"></script>
        <!--<script type="text/javascript" src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>-->

        <!-- Toastr -->
        <script src="{% static 'base/js/toastr.min.js' %}"></script>

        <script src="{% static 'base/jquery_confirm/jquery-confirm.min.js' %}"></script>

        <!-- XDSoft DateTimePicker -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

        <!-- Bootstrap Table -->
        <!--<script src="{% static 'base/bootstraptable/dist/bootstrap-table.min.js' %}"></script>-->
        <!--<script src="{% static 'base/bootstraptable/dist/bootstrap-table-locale-all.min.js' %}"></script>-->
        <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>
        <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table-locale-all.min.js"></script>
        <!-- Select2 -->
        <script src="{% static 'base/js/select2.min.js' %}"></script>
      </div>

    <script>
    $(document).ready( function () {
        $('#tabla').DataTable({
            "order": [[ 1 ,"desc" ]],
            "language": {
            "sProcessing": "Procesando...",
            "sLengthMenu": "Mostrar _MENU_ registros",
            "sZeroRecords": "No se encontraron resultados",
            "sEmptyTable": "Ningún dato disponible en esta tabla",
            "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix": "",
            "sSearch": "Buscar:",
            "sUrl": "",
            "sInfoThousands": ",",
            "sLoadingRecords": "Cargando...",
            "oPaginate": {
                "sFirst": "<span class='fa fa-angle-double-left'></span>",
                "sLast": "<span class='fa fa-angle-double-right'></span>",
                "sNext": "<span class='fa fa-angle-right'></span>",
                "sPrevious": "<span class='fa fa-angle-left'></span>"
            },
            "oAria": {
                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
        }
        });
    });
    </script>
</body>
</html>

templates/side_bar.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold"></span>
                        <span class="text-muted text-xs block">Bienvenido <b></b></span>
                    </a>
                </div>
                <div class="logo-element">
                </div>
            </li>

            <li>
                <a href="#"><i class="fa fa-list"></i> <span class="nav-label">Listados</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{% url 'apiv1:ranking_sellers' %}"><i class="fa fa-money"></i> Vendedores - Top 5</a></li>
                    <li><a href="{% url 'apiv1:ranking_publishings' %}"><i class="fa fa-send"></i> Publicaciones</a></li>
                    <li><a href="{% url 'apiv1:connect_ml' %}"><i class="fa fa-plug"></i> Conectar a Meli</a></li>
                </ul>
            </li>

        </ul>
    </div>
</nav>

templates/top_bar.html
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">

        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li style="padding: 20px">
                <span class="m-r-sm text-muted welcome-message">Real Trends</span>
            </li>
        </ul>
    </nav>
</div>